server:
  port: 5000
spring:
  cloud:
    gateway:
      routes:
        # oss服务
        - id: oss
          uri: lb://jc-club-oss
          predicates:
            - Path=/oss/**
          filters:
            - StripPrefix=1

        # auth服务
        - id: auth
          uri: lb://jc-club-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # subject服务
        - id: subject
          uri: lb://jc-club-subject
          predicates:
            - Path=/subject/**
          filters:
            - StripPrefix=1